### ISSUE TITLE
FilterQueryValidator is not a singleton

### ISSUE THREAD

**Issue by 9Rune5** [OData/WebApi#1109]
I am using the OData60 branch, and have been trying to figure out why my odata service keeps telling my clients that certain properties can't be used in a $filter expression.

> The property 'BorrowerId' cannot be used in the $filter query option."

I constructed a test client that runs intermittent calls to two different controllers, and eventually I managed to trip over the bug myself. It was validating properties from one call with the entity referred to by the other call.

`            builder.AddService<FilterQueryValidator>(ServiceLifetime.Singleton);
` (System.Web.OData\Extensions\ContainerBuilderExtensions.cs)

Looks like a bug. The FilterQueryValidator is definitively not reusable in its present state. There is a Validate() method that accepts quite a few arguments that are then stored as field and used later during validation. 

I believe the correct ServiceLifetime should be `Scoped`.

**Comment by 9Rune5** [comment]
A colleague points out that this bug has already been fixed (https://github.com/OData/WebApi/commit/3a312d71370352458e1627f4f735af70ac7dd1b5#diff-96010717bc56d22c49c07e90c0e3252f).

So... Could we have this fix in a NuGet package somewhere please?

**Comment by karl-sjogren** [comment]
3a312d71370352458e1627f4f735af70ac7dd1b5 was against the master branch, we would need the fix made in #1098 to be applied to OData60 as well. Cherry picking the commits seems to merge cleanly.

**Comment by robward-ms** [comment]
OData60 is a old branch, we plan to get rid of it once all PRs against it are processed. It has been superseded by the master branch.

The fix is in the master branch but we have not released WebApi since the fix. Our next scheduled release is next month.

The fix is available in the nightly package (Be advised we only keep the 10 most recent nightly packages): https://www.myget.org/feed/webapinightly/package/nuget/Microsoft.AspNet.OData

**Comment by 9Rune5** [comment]
@robward-ms wrote "next month" back in October. Any updates on the update? :)
