### ISSUE TITLE
Custom MetadataController is called but caller still receives default model

### ISSUE THREAD

**Issue by lukred** [OData/WebApi#1130]
My OData service has authorization (different users must see different OData model - that is: different /$metadata and different service document).

I've written my own routing convention (just for tests).

var conventions = ODataRoutingConventions.CreateDefault();
conventions.Clear();
conventions.Add(new MetadataRoutingConventionNew());

Inside MetadataRoutingConventionNew, I've redefined the controller which should be executed when user asks for /$metadata:

 if (odataPath.PathTemplate == "~" || odataPath.PathTemplate == "~/$metadata")
return "NewMetadata";

And I have a class:

NewMetadataController: ODataController

In which I have my custom impl of:
public IEdmModel GetMetadata()
{
...
}

### Assemblies affected

Microsoft.AspNet.OData 6.1.0

### Expected result

User should see my custom model when he browse /$metadata

### Actual result

My code within NewMetadataController is fired.

When user asks for service document - it works! - he sees different data
When user asks for /$metadata - it does not work. 
User always sees the metadata for model which was defined in 
config.MapODataServiceRoute(...)

Even though my custom GetMetadata() is called!

**Comment by xuzhg** [comment]
It uses the `Model` from `Request` to create the `MessageWriter`, see codes https://github.com/OData/WebApi/blob/master/src/System.Web.OData/OData/Formatter/ODataMediaTypeFormatter.cs#L513

And the MetadataSerializer has the following assumption: https://github.com/OData/WebApi/blob/master/src/System.Web.OData/OData/Formatter/Serialization/ODataMetadataSerializer.cs#L32-L33

That's why your customized model can not be used in serializer.

I have doubt why you set the service using one model and return $metadata using a customized model?
However, I think you can write your own Metadata Serializer by creating your own `ODataMessageWriter` object using your own `Model`.

**Comment by lukred** [comment]
Hello
Thank you for the quick answer.

However, I'm not sure if I understood it well.
Which class should I overwrite (write own impl) and how to use it then?
Also, If I understand you correctly, I don't need my own routing conventions and controller at all right? 

(The retionale is that I want to hide specific entity sets for specific users - so there is kinda authorization. They should not even see some entity sets).

**Comment by xuzhg** [comment]
@lukred 

Sorry for later response. I wrote an Ugly workaround to meet your requirement.  
See at:
https://github.com/xuzhg/WebApiSample/commit/b16a788843db4ea790fa08efe63d9a58c336582d

Let me know any concern.

**Comment by xuzhg** [comment]
I closed it. Thanks your feedback. Please re-open it or file new issue if you have further concerns.
