### ISSUE TITLE
Asp .NET Core [feature / netcore]

### ISSUE THREAD

**Issue by ErliSoares** [OData/WebApi#1177]
Error making request using [EnableQuery] and ODataController controler
![image](https://user-images.githubusercontent.com/2334509/34284733-595ac258-e6bb-11e7-988f-2af1fed8e3ec.png)

**Comment by robward-ms** [comment]
@ErliSoares - Can you provide some information about your startup, controller and the request url?

**Comment by robward-ms** [comment]
Possibly a dup of #1175?

**Comment by robward-ms** [comment]
@ErliSoares - Yep, it's a new issue that was caused by a last minute change. It occurs when a request is made on a non-OData route, which your project is configured to open (look in project properties, debug, app URL for the default URL). If you make a request against the configured OData endpoint, it should work as expected.

You can work around this issue by adding the following inside the UseMvc lambda, right below the call to MapODataServiceRoute(): 

routes.EnableDependencyInjection();

Where routes is the name of the IRouteBuilder lambda parameter.

**Comment by ErliSoares** [comment]
Many thanks for the feedback.
Take the delay, but it did not work to put the route.EnableDependencyInjection ();

I try to access a URL from a Swagger-generated file, but when I access the URL:
> http://localhost:32769/api-docs/v1/swagger.json
This error occurs:
> `System.InvalidOperationException: No media types found in 'Microsoft.AspNet.OData.Formatter.ODataInputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
   at Microsoft.AspNetCore.Mvc.Formatters.InputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.GetRequestFormats(IApiRequestMetadataProvider[] requestMetadataAttributes, Type type)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

My Startup class: [Startup.txt](https://github.com/OData/WebApi/files/1584316/Startup.txt)

**Comment by robward-ms** [comment]
@ErliSoares - Looks like routebuilder.EnableDependencyInjection(); changed the error. It used to be the same error as #1175 but now the new exception looks like #1176, which you also filed. Do I have that correct? If so, lets us this one to track the 'No media types found' issue and close #1176 (since this one has more info).

I see you had added some code to add a media type to the odata formatters. This is close to the workaround I would suggest (but have not tried) except you are targetting the output formatters collection, not the input formatters. For the second block of code in your UseMvc(), I suspect something like this would work-around the issue:

foreach (var **input**Formatter in options.**Input**Formatters.OfType<Microsoft.AspNet.OData.Formatter.ODataInputFormatter>().Where(...))
{
  ...
}

There is one input formatter being added by OData without any media types but it should be skipped for non-OData requests: https://github.com/OData/WebApi/blob/f140814fa7a300a88dad259124ddf45de6682bc0/src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatter.cs#L94-L98

Either removing it from the list of giving it a media type should mitigate the issue.

**Comment by ErliSoares** [comment]
'options.InputFormatters' worked.
Other errors that influenced, but it was mapping of the Entity Framework.

Thank you very much.

**Comment by eloekset** [comment]
I'm having the same issue now. Exactly where did you put that *foreach (var inputFormatter in ...)* code?

**Comment by acjh** [comment]
# Workaround

```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        services.AddOData();

        // Workaround: https://github.com/OData/WebApi/issues/1177
        services.AddMvcCore(options =>
        {
            foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
            {
                outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
            }
            foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
            {
                inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
            }
        });
    }
    
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {                
        var builder = new ODataConventionModelBuilder(app.ApplicationServices);

        builder.EntitySet<Product>("Products");

        app.UseMvc(routebuilder => 
        {
            routebuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
            
            // Workaround: https://github.com/OData/WebApi/issues/1175
            routes.EnableDependencyInjection();
        });
    }
}
```

**Comment by christianquirante** [comment]
Good day everyone, how come when I added MediaTypeHeaderValue I got this error

'cannot convert from 'System.Net.Http.Headers.MediaTypeHeaderValue' to 'Microsoft.Net.Http.Headers.MediaTypeHeaderValue'?

Is there something I am missing here?

**Comment by christianquirante** [comment]
if I put this code 

r.MapODataServiceRoute("ODataRoute","odata", builder.GetEdmModel(), new DefaultODataBatchHandler()); 

the odata doesn't show up and it says this "This localhost page can’t be found" 

but when I use this code the odata shows up 

r.MapODataServiceRoute("odata",null, builder.GetEdmModel(), new DefaultODataBatchHandler()); 

can someone explain why this is happens?

**Comment by christianquirante** [comment]
there is no paths and definitions when I clicked this "/swagger/v1/swagger.json" at swagger

https://localhost:44361/swagger/v1/swagger.json

{"swagger":"2.0","info":{"version":"v1","title":"OData API"},"paths":{},"definitions":{}} 

Is this related as to why it shows 'No operations defined in spec!' at localhost:44361/swagger/…?

**Comment by Kizmar** [comment]
@christianquirante As far as I can tell, Swagger doesn't support using OData in AspNetCore. If all you have are OData endpoints, that message is likely pointing this fact out. We have regular Controllers in our API in addition to the OData controller, and our Swagger works, but we aren't seeing the OData endpoints.

**Comment by julealgon** [comment]
I have been playing with OData for the past few weeks and it was working fine until today. Suddenly, I started getting this error in swagger.

I honestly have no idea what exactly caused it to start breaking... the workaround of adding a dummy media type on the raw input formatter worked, but this is really scary stuff.

I'm actually assuming that reflection order somewhere is causing the behavior to change, because this started occurring on my end after adding a bunch of completely unrelated helper classes and such.

@KanishManuja-MS I know we've been discussing a few unrelated issues recently. Do you have any idea whatsoever about why this issue would start cropping up suddenly like I described above? I have literally changed NOTHING on my startup class logic: I extracted the EDM model builder into a separate class, added a few mappers and helpers, and when I went to test my changes I remembered "hey let's see swagger again" and it was broken.

Honestly, while the workaround above does work, it makes absolutely no sense to me and I'd rather avoid the confusing extra line of code in my codebase (BTW, only the raw input formatter needs to be touched. Lookping over output formatters has no effect as far as I could tell).

**Comment by commonsensesoftware** [comment]
It would appear there wasn't a very strong effort to determine the root cause of this. It took some spelunking, but I found it. The **ODataOutputFormatter** is not implemented correctly. It supports a scenario (validly for OData only) where the media type is derived from the incoming request and thus the formatter doesn't have any predefined media types. This breaks the inherited functionality of **OutputFormatter**. I've filed this issue as #1750. The fix is trivial.

The out-of-the-box implementations of OData inherently do not support the API Explorer, which is likely why these types of issues have not be discovered by the team or in testing.

**Comment by NBroomfield** [comment]
This might help some people?

https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample

**Comment by commonsensesoftware** [comment]
@NBroomfield thanks for the plug, but as the author of the example that you've referenced, it works because I handle and ignore the **InvalidOperationException** that gets produced. I hadn't previously figured out why this was happening. The referenced example will **only** work if you use OData exclusively. If you're mixing OData with non-OData controllers **and** Swagger, then this problem will crop back up (as I found). There isn't really a way to get _in front_ of the issue, which is why it _should_ be fixed in OData as it's the source of the behavioral change.

There are at least 3 interim workarounds:

1. Remove the **ODataOutputFormatter** that has no registered media types (there's only 1)
    a. This is an easy solution if you don't need the _raw_ support
2. Add **any** media type to the offending **ODataOutputFormatter** (as previously suggested)
    a. The prevents the exception because the formatter never uses `GetSupportedContentTypes`
    b. This will report a bogus media type that you might have to exclude or change elsewhere for Swagger
3. Adapt over or replace the offending **ODataOutputFormatter** with an implementation that does the correct thing
   a. Consumers of **InputFormatter** and **OutputFormatter** already expected `GetSupportedContentTypes` to return `null` or an empty list

**Comment by NBroomfield** [comment]
@commonsensesoftware, thanks for the reply, that's really useful feedback, do you know if NSwag will work with Odata and dot net core?

**Comment by commonsensesoftware** [comment]
I don't have a working sample, but - **yes** - it will work.

Unlike some other libraries that have provided Swagger support for OData in the past, API versioning isn't providing any direct Swagger support. What it provides is solid support for the _API Explorer_ API. Tools, such as Swagger generators like Swashbuckle and NSwag, then rely on _explored_ information to do their work. In this way we are _symbiotic_ without any direct dependencies on each other.

Based on a previous conversation with the author of NSwag, I know there was some work being done in the more recent versions to make things more easily light up. You'll need the following packages:

* API Versioning for OData on ASP.NET Core
* API Versioning API Explorer for OData on ASP.NET Core
* NSwag

For more information and NSwag configuration, you'll probably want to visit the NSwag repo. The API Explorer integrate is always the same. You just need: `services.AddODataApiExplorer()`.

I hope that help.s

**Comment by ddunhill** [comment]
FYI in case it catches anyone else out. 
In the above fix it is important that the line 
`services.AddOData();`
comes before the line
`services.AddMvcCore(options =>`

It took me awhile to spot that one...

**Comment by cecilphillip** [comment]
@commonsensesoftware just curious. Wouldn't it be acceptable if the Raw ODataInputFormatter supported tex/plain as a media type?

**Comment by GustavoAmerico** [comment]
> # Workaround
> ```cs
> public class Startup
> {
>     public void ConfigureServices(IServiceCollection services)
>     {
>         services.AddMvc();
> 
>         services.AddOData();
> 
>         // Workaround: https://github.com/OData/WebApi/issues/1177
>         services.AddMvcCore(options =>
>         {
>             foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
>             {
>                 outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>             }
>             foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
>             {
>                 inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>             }
>         });
>     }
>     
>     public void Configure(IApplicationBuilder app, IHostingEnvironment env)
>     {                
>         var builder = new ODataConventionModelBuilder(app.ApplicationServices);
> 
>         builder.EntitySet<Product>("Products");
> 
>         app.UseMvc(routebuilder => 
>         {
>             routebuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
>             
>             // Workaround: https://github.com/OData/WebApi/issues/1175
>             routes.EnableDependencyInjection();
>         });
>     }
> }
> ```

This answer should be in the documentation

**Comment by robcube** [comment]
> > # Workaround
> > ```cs
> > public class Startup
> > {
> >     public void ConfigureServices(IServiceCollection services)
> >     {
> >         services.AddMvc();
> > 
> >         services.AddOData();
> > 
> >         // Workaround: https://github.com/OData/WebApi/issues/1177
> >         services.AddMvcCore(options =>
> >         {
> >             foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
> >             {
> >                 outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
> >             }
> >             foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
> >             {
> >                 inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
> >             }
> >         });
> >     }
> >     
> >     public void Configure(IApplicationBuilder app, IHostingEnvironment env)
> >     {                
> >         var builder = new ODataConventionModelBuilder(app.ApplicationServices);
> > 
> >         builder.EntitySet<Product>("Products");
> > 
> >         app.UseMvc(routebuilder => 
> >         {
> >             routebuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
> >             
> >             // Workaround: https://github.com/OData/WebApi/issues/1175
> >             routes.EnableDependencyInjection();
> >         });
> >     }
> > }
> > ```
> 
> This answer should be in the documentation

Do you mean: `**routebuilder**.EnableDependencyInjection();` ?

Otherwise, it was the solution for me too.

**Comment by Pzixel** [comment]
Works to me. Important note: formatters must be fixed AFTER odata is registered. This is why my original code `AddMvc(...).AddOData()` didn't work. Be careful.

**Comment by AmirSasson** [comment]
for some reason, i still don't know why.
when using the above solution (or upgrade the package), the request for /swagger/SOMEVERSION/swagger.json is stuck and doesnt return at all.
no exception that i am getting.
this is the code i am using:
```csharp
   services.AddOData();
           
   services
        .AddControllers(options =>
        {           
               foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    outputFormatter.SupportedMediaTypes.Add(new Net.Http.Headers.MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
                foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    inputFormatter.SupportedMediaTypes.Add(new Net.Http.Headers.MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }             
        })

**Comment by julealgon** [comment]
@AmirSasson you should consider opening a separate issue to get more traction on your problem. Even if they are related, this has already been closed as "fixed" and it might be better to document the new problem separately and link this one to it.
