### ISSUE TITLE
OData Controllers and Reflection

### ISSUE THREAD

**Issue by TonyValenti** [OData/WebApi#1185]
Hi All,
I am doing my first foray into OData and MVC and I'm bumping into one issue that I'm hoping I can get some help with.

I have about 50 different classes that all have a common base type.  Using generics, I'd like to expose all these objects through OData.  I've got this code that I've written:
````
        private static IEdmModel GetEdmModel(IServiceProvider serviceProvider) {
            var ret = default(IEdmModel);
            var builder = new ODataConventionModelBuilder(serviceProvider);

            foreach (var item in SharedApiClient.Instance.APIs) {
                if (item is ICachedCrudApi API) {
                    builder.EntitySet(API.TJson.Name, API.TJson);
                }
            }
            ret = builder.GetEdmModel();

            return ret;
        }
````

That get's me half of the way there.  I then have a generic class like so:
````
public class CommonApiController<TJson> : ODataController {
        public virtual IEnumerable<TJson> Get(ODataQueryOptions<TJson> options) {
                //truncated for brevity
        }
        
        public virtual async Task<TJson> Get([FromODataUri] long key) {
                //truncated for brevity
        }

    }
````

What I'd like to do is create all of my endpoints programmatically without having to create a bunch of repetitive boilerplate classes like this:
````
public class UserApiController : CommonApiController<UserJson> { }
public class ContactApiController : CommonApiController<ContactJson> { }
///etc
````

How do I expose the controllers?

**Comment by biaol-odata** [comment]
@TonyValenti Thanks for your interesting in OData. If I understand your intention correctly, if your various controllers don't contain any overrides, you can just use, for example CommonApiController<UserJson> directly instead of the UserApiController w/o overrides, right? If it needs overrides, it does need a new class definition with overriding logic anyway.

Also, questions like this should be posted to stackoverflow, where it can get better community support. Maybe others can offer their similar experience related to your questions there. Issues in gitub is the primarily for bug reports and feature requests.
