### ISSUE TITLE
[feature/netcore] FilterQueryOption.ApplyTo requires ODataQueryContext.RequestContainer

### ISSUE THREAD

**Issue by afaganga** [OData/WebApi#1194]
FilterQueryOption.ApplyTo throws on UpdateQuerySettings because ODataQueryContext.RequestContainer is null

### Assemblies affected

Microsoft.AspNet.OData 7.0.0

### Reproduce steps

```
            var model = GetEdmModel();
            var uriParser = new ODataUriParser(
                model, 
                new Uri("http://gobbldygook/"), 
                new Uri("http://gobbldygook/Vegetables?$filter=Id eq 1"));

            var path = uriParser.ParsePath();

            var context = new ODataQueryContext(model, typeof(Vegetable), null);
            var parser = new ODataQueryOptionParser(
                model, 
                path, 
                new Dictionary<string, string>(){{"$filter","Id eq 1"}});

            var filterQueryOption = new FilterQueryOption("Id eq 1", context, parser);

            var queryable = Enumerable.Empty<Vegetable>().AsQueryable();
            filterQueryOption.ApplyTo(queryable, new ODataQuerySettings()); // throws
```

### Expected result

queryable had an Expression

### Actual result

throws ArgumentNullException

### Additional detail
Exception detail

ArgumentNullException: Value cannot be null. Parameter name: provider
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
Microsoft.AspNet.OData.ODataQueryContextExtensions.UpdateQuerySettings(ODataQueryContext context, ODataQuerySettings querySettings, IQueryable query)
Microsoft.AspNet.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)

**Comment by robward-ms** [comment]
@afaganga - Yep, ODataQueryContext is public with no public way to set the container; only ODataQueryOptions sets it.

Given that this method tries to copy the settings from the passed in parameter and update the HandleNullPropagation property, maybe it makes sense to just skip the update when no request container is available. Thoughts?

**Comment by afaganga** [comment]
That should do it. Also, it could make sense to have a way to set the container.
The underlying use case is to extract an Expression<Func<TSource, Boolean>>, enabling an IObservable<TSource> usage; As such, I feel parsing should not even need aspnet at all - probably this should be a part of the EdmLib bundle.

**Comment by robward-ms** [comment]
I tried a fix to allow the container to be null in UpdateSettings:

```
            ODataQuerySettings updatedSettings = context.RequestContainer != null
                ? context.RequestContainer.GetRequiredService<ODataQuerySettings>()
                : new ODataQuerySettings();
```

But then your scenario throws in Bind() where is creates a FilterBinder(), which takes the container as a constructor argument and passes it to it's base class. To make the container optional for the scenario would mean making it optional down (at least) this class tree.

Given that the UTs test these scenarios (they do) by settings the RequestContainer, which it can do since it has access to internals, the safest fix is to make RequestContainer public. Otherwise, I think we could construct a (narrow) fix for this particular issue and miss some others.

However, that requires you to set it and populate it with a host of classes. Ideally, the method that does this population would also be available for public use to make it easier to construct. So if it's not, that should also be part of the fix.

The public RequestContainer is the approach I'm inclined to implement. Thoughts?

**Comment by robward-ms** [comment]
FYI, I opted to make a series of changes to make the RequestContainer optional as it was more in the spirit of the original DI design. The repro has been used as a unit test.

**Comment by vmandic** [comment]
Hello, I encountered this also unfortunately. :-( 
Any release plans / ideas on this fix please, any rough est. at least? 

Thank you very much.

**Comment by robward-ms** [comment]
@vmandic - Have you tried the nightly build which contains the fix?

**Comment by vmandic** [comment]
@robward-ms thanks!! Built my FQO without errors, didn't remember to hook on with nightly builds via: https://www.myget.org/F/webapinetcore/api/v3/index.json 👍

**Comment by xuzhg** [comment]
close it and please file new issue if you have further concern. Thanks.
