### ISSUE TITLE
OData vs Entity Framework TOP x

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1210]
Apparently OData adds an ORDER BY clause to a query when a ?$top is used. Entity Framework does not add this when using a .Take(). This is causing us issues currently on a cross database view which is unable to have an index. The order by increases the query time by **3000%**.

Is there a way to override this behaviour?

On top of this I've also noticed that when a ?$top is used any .OrderBy() added in code is ignored and overwritten with an ORDER BY on the primary key. This is not the case when using ?$filter for example.

Here are the logs of the queries being sent to the database.

OData (http://localhost:/Items?$top=2):
Closed connection at 18/01/2018 11:49:35 +01:00
Opened connection at 18/01/2018 11:49:35 +01:00
SELECT TOP (@p__linq__0) 
    [Extent1].[...] AS [...],
    [Extent1].[...] AS [...]
    FROM [...] AS [Extent1]
    **ORDER BY [Extent1].[...] ASC**
-- p__linq__0: '2' (Type = Int32, IsNullable = false)
-- Executing at 18/01/2018 11:49:36 +01:00
-- Completed in 111 ms with result: SqlDataReader

Closed connection at 18/01/2018 11:49:37 +01:00

Entity Framework (http://localhost:/Items and adding a .Take(1000) in code):
Closed connection at 18/01/2018 11:49:37 +01:00
Opened connection at 18/01/2018 11:56:29 +01:00
SELECT TOP (1000) 
    [c].[...] AS [...],
    [c].[...] AS [...]
    FROM [...] AS [c]
-- Executing at 18/01/2018 11:56:29 +01:00
-- Completed in 221 ms with result: SqlDataReader

Closed connection at 18/01/2018 11:56:29 +01:00

**Comment by bdebaere** [comment]
I have found a property EnsureStableOrdering in ODataQuerySettings. With an override on EnableQueryAttribute I was able to change this value to false. Is this the correct approach?

**Comment by NetTecture** [comment]
> This is causing us issues currently on a cross database view which is unable to have an index. The order 
> by increases the query time by 3000%.

This is extremely bad design - firing bad. Without an order by, TOP on a SQL level is not stable. I.e. you can get different results in different queries. SQL basics demand that you define an order if you need one, and as top is used in paging, you need the paging to be stable. How unstable? Well, it may change with a hotfix. Sometimtes it may really change between requests.

> On top of this I've also noticed that when a ?$top is used any .OrderBy() added in code is ignored

That makes sense - $top comes last. You should be able to add an order in the odata request, which - again , is what you should do if you do not want key ordering ;) This would allow you to use a more "Performance oriented" stable ordering. In many cases the PK may suck - mine is regularly a GUID, so it effectively is random - but tehre are more natural sort properties on many classes (which also are alternate keys).

**Comment by bdebaere** [comment]
> Without an order by, TOP on a SQL level is not stable. I.e. you can get different results in different queries.
This is simply untrue. If you have a primary key in your table the order in which the results are returned will always be determined by it.

**Comment by NetTecture** [comment]
That is a typical beginner mistake, sorry.

It is stable as long as the query plan does not change (and is reused). Which may happen when the underlying data changes.

There is no guarantee - the specific issue here is quarantee - tat the primary key will be used. In particular, the PK on database level will only be used if it is also the clustered index (in case of SQL server). But unless you can guarantee that statistics does not change and the query plan is not invalidated - no, it is not guaranteed. It is the case 99% of the time, and it is a sign of a bad programmer to assume an explicitly not documented behavior is stable because his limited exprerience shows this. You want an order, you put in an order by statement, or you do not ahve a guarantee.

Now, you may say "but I talk about odata", in which case I kindly point out that you obviously failed to ven bother reading the discussion - because yes, odata does implicitly add the primary key as order by lause, and this is exactly what the OP is complaining about, as it causes a significant raise in processing time for him. And why does odata add an order by? Ah, because sql otherwise is not stable.

I suggest you read up on database basics.

**Comment by bdebaere** [comment]
If the primary key is not also the clustered index then that is just bad database design. Even so, the original question was how to remove the order by clause, meaning the order by is not necessary and the order does not matter.

Can you show me an example where a SELECT returns results in a different order when the primary key is the clustered index? If so, then today I learned.

**Comment by NetTecture** [comment]
Examples are hard to come by, but they generally go around this:

* You have a where clause
* Due to database changes the statistics change enough so that a better query path is assumed.

Remember that I think statisatics are only updated when 20% of the rows have changed - over time. So it is possible that you are just on the threshhold for days, then some changes mean a new statistics and thus a different query path.

This is not really often the case for simple queries, but... not all queries are simple. Conditions can be extremely complex, query paths can be complex when some of the data you return comes from views.

An example I would give is for example change of access. Suddenly the query may return a lot LESS data (because someone removed reading rights on most data). Suddenly SQL Server decides that using the primary key (on the original data) is not really efficient, it is better to first find out which elements to return, (which may come in whatever order) and then loop over them. Between two queries you went from an original set of "all the data" (admin rights) to "20 elements max" (only one small customer) and thus the query plan totally flips.

Another example is actually workong in a non trivial database size. One where timing of multiple read streams may determine order. See, if your data queries is large enough, sql server may actually paralellize the query.... and in this case you start depending on timing behaviors of different threads to get the exact order.

https://blogs.msdn.microsoft.com/conor_cunningham_msft/2008/08/27/no-seatbelt-expecting-order-without-order-by/

Not knowing this is a well documented beginner trap - the SQL Standard and the sql sever documentatio nare pretty clear on no guarantees given unless asked for (which is why Odata assumes primary key).

Look at

https://stackoverflow.com/questions/15522746/is-sql-order-by-clause-guaranteed-to-be-stable-by-standards

and if you want it "face paln you never read documentation" trivial, read https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-2017 - quote: "The order in which rows are returned in a result set are not guaranteed unless an ORDER BY clause is specified."

**Comment by bdebaere** [comment]
Thanks for taking the time for your explanation.

**Comment by JairoMarques** [comment]
If you don't care about a Stable Ordering, a simple way is put EnableQuery attribute like this:
`[EnableQuery(EnsureStableOrdering = false)]`
