### ISSUE TITLE
AddODataQueryFilter with EnableQueryAttribute doesn't work

### ISSUE THREAD

**Issue by aelij** [OData/WebApi#1265]
Using `AddODataQueryFilter(new EnableQueryAttribute { ... })` doesn't seem to have any effect. Filtering is not enabled, and we must add `[EnableQuery]` on every controller. Additionally, values such as `PageSize` are ignored when using `AddODataQueryFilter` (but do work using the attribute on a controller).

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0-beta1

**Comment by biaol-odata** [comment]
@aelij I believe HttpConfiguration.AddODataQueryFilter should work and it is supported on the classic Aspnet.OData side. But you mentioned AspNetCore assembly, How did you invoke the method? Thanks.

**Comment by biaol-odata** [comment]
@aelij Looks like you are using ODataServiceCollectionExtensions.AddODataQueryFilter(IActionFilter)? Can you add/ensure the followings in your service:

- Invoke AddODataQueryFilter above during service startup.
- Enable needed query settings in route builder. For example, app.UseMvc(builder => { builder.Select().Expand().Filter().OrderBy().MaxTop(100).Count();...});

You can refer to the modified test ODataTypeAnnotationShouldAppearForComplexTypesLikeCollectionAndUserDefinedTypes in my forked repo https://github.com/OData/WebApi/compare/master...biaol-odata:issue1265, which shows working query filter "/Complex/EntityWithComplexProperties?$select=StringListProperty" when JObject is returned correctly on & after L66.

Please let's know whether that resolves the issue. Thanks.

**Comment by aelij** [comment]
@biaol-odata  This is how our startup looks:

```csharp
public class Startup
{
    public void  ConfigureServices(IServiceCollection services)
    {
        services.AddOData();

        services.AddODataQueryFilter(new EnableQueryAttribute
        {
            AllowedQueryOptions = AllowedQueryOptions.All,
            PageSize = 10,
            MaxNodeCount = 20,
        });
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        app.UseMvc(routeBuilder =>
        {
            routeBuilder.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
            var odataModel = app.ApplicationServices.GetService<IEdmModel>();
            routeBuilder.MapODataServiceRoute("ODataRoute", "api/odata", odataModel);
            routeBuilder.EnableDependencyInjection();
        });
    }
}
```

I will try the latest version when I get a chance and see if there's any change.

**Comment by biaol-odata** [comment]
@aelij Please let us know whether this issue has been resolved. We are trying to scrub the issues.

**Comment by biaol-odata** [comment]
@aelij I believe the ODataServiceCollectionExtensions.AddODataQueryFilter(IActionFilter) works as expected, therefore I am closing it now. Feel free to re-open it if it is not the case; or open new issues for other observations so that we can address them properly. Thanks.

**Comment by norcino** [comment]
@biaol-odata  I been trying to understand the logic behind _ODataServiceCollectionExtensions.AddODataQueryFilter(IActionFilter)_ but still to me does not make sense.

So to recap, we have different options we can use to configure OData capabilities.

1) Service collection AddODataQueryFilter (allow to set page size)
2) In UseMvc RouteBuilder extension methods: .Select().Filter().OrderBy() .. (no page size setup)
3) In UseMvc RouteBuilder using SetDefaultQuerySettings, this is the same as the extension methods above, including the limitation for the page size.
4) Attribute configuration "EnableQueryAttribute"

Now, if I use AddODataQueryFilter without having first set SetDefaultQuerySettings, nothing will work, so why you give me the possibility to customise the odata filter as shown below?

The fact that is possible to configure the allowed query options as shown
```
services.AddODataQueryFilter(new EnableQueryAttribute
{
     // I want to allow OrderBy and Filter only
    AllowedQueryOptions = AllowedQueryOptions.OrderBy | AllowedQueryOptions.Filter,
    PageSize = configuration.GetValue<int>("OData:PageSize"),
    MaxNodeCount = configuration.GetValue<int>("OData:MaxNodeCount"),
});
```
clashes with the **SetDefaultQuerySettings**, which has priority compared to the **AllowedQueryOptions**.

````
app.UseMvc(routeBuilder => {
    routeBuilder.MapODataServiceRoute("odata", "{tenant}/odata", serviceProvider.GetService<IEdmModelProvider>().GetModel(serviceProvider));
    routeBuilder.Select().Filter().OrderBy().MaxTop(100) ...;
````

This means that if I set _Select_ enabled in **SetDefaultQuerySettings** and I don't allow it in **AllowedQueryOptions**, _Select_ will still be allowed to the user.
If instead i do not specify _Select_ in **SetDefaultQuerySettings**, but I do allow it, it won't work anyway.

So to me it looks like **AllowedQueryOptions** is useless and just misleading, but because I think that nothing is there without a reason, can anyone please explain to me?!

Also, to globally set pagination limit the only way is to use _AddODataQueryFilter_, but what seems to be the real driver, _SetDefaultQuerySettings_, does not allow to handle pagination, so if you avoid to use the first, you can only do it at attribute level.
