### ISSUE TITLE
Contains does not perform a search

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1451]
A contains does not perform a search, instead it searches for complete matches.

### Assemblies affected

Latest.

### Reproduce steps

Test contains().

### Expected result

When entering the following OData query /Customers?$filter=contains('a', Name). I should receive a result of all customers containing an "a" in their Name e.g. Amazon.

### Actual result

I receive nothing.

### Additional detail

The SQL log shows that the CHARINDEX used should be reversed. 
Currently it states `WHERE ( CAST(CHARINDEX([Extent1].[Name], @p__linq__0) AS int)) > 0`.

It should be `WHERE ( CAST(CHARINDEX(@p__linq__0, [Extent1].[Name]) AS int)) > 0`

**Comment by xuzhg** [comment]
@bdebaere 

From OData spec, it says : The contains function with string parameter values returns true if the *second* string is a substring of the first string, otherwise it returns false. "

In your example, the value of `Name` is a substring of `a`?  So, I think you suppose to use :  `$filter=contains(Name, 'a')`.

If you try our [sample project](https://github.com/OData/WebApi/tree/master/samples/AspNetCoreODataSample.Web), It can work as:

 ```C#
http://localhost:5913/inmem/Movies?$filter=contains(Title, 'C')
```

**Comment by xuzhg** [comment]
Close it and please let us know further concerns. Thanks.
