### ISSUE TITLE
Expand Filter Not Working

### ISSUE THREAD

**Issue by stumpykilo** [OData/WebApi#1520]
Expand seems to work fine but when I go to filter it like this:
https://localhost:5006/api/Items?$expand=Skus($filter=VendorId eq 5)
It still brings back all items with empty Skus except for one item that matches the filter.

That's not how this is supposed to work, right? I'd expect to only get back the one item.

I'm using the Latest stable 7.0.0 version in a .NET Core 2.1.1 web api.

**Comment by stumpykilo** [comment]
Actually, I just read this documentation and I'm getting the expected results:
http://odata.github.io/WebApi/#04-03-filter-in-expand

How would I get back only the items that do have children that satisfy the filter?

**Comment by xuzhg** [comment]
@stumpykilo would you please give an example about "How would I get back only the items that do have children that satisfy the filter?"

**Comment by stumpykilo** [comment]
{
	Id = 1,
	Name = "abc",
	Orders = new[]
	{
		new Order { Id = 10, Name = "xyz" },
                new Order { Id = 11, Name = "def" },
	}
},
{
	Id = 2,
	Name = "def",
	Orders = new[]
	{
		new Order { Id = 12, Name = "lmn" },
                new Order { Id = 13, Name = "ghi" },
	}
}
https://localhost/api/Items?$expand=Orders($filter=Name eq 'ghi')
I would want just the 2nd item to return.

**Comment by xuzhg** [comment]
@stumpykilo 
I think you are looking the following query option:
`
~/Items?$filter=Orders/any(o:o/Name eq 'ghi')

`


It will only give you the 2nd one.

**Comment by xuzhg** [comment]
@rdmpark I think that's by design. 

See the comments from OData spec:

_Example 40: for each customer entity within the Customers entity set, the value of those related Orders whose Amount is greater than 100 will be represented inline
`GET http://host/service.svc/Customers?$expand=Orders($filter=Amount gt 100)`_

So, 

- `GET http://host/service.svc/Customers`  returns all customers
- `GET http://host/service.svc/Customers?$filter=Name eq 'abc'`  returns all customers whose name equals to 'abc'
- `GET http://host/service.svc/Customers?$expand=Orders`  returns all customers, and for each Customer, inline Orders
- `GET http://host/service.svc/Customers?$expand=Orders($filter=Amount gt 100)`  returns all customers, for each Customer, inline Orders only order's amount gt 100.


I'd like @mikepizzo help me to confirm it.
