### ISSUE TITLE
CORS preflight doesn't work with OData in ASP.NET Core

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/WebApi#1611]
Sending CORS preflight requests to an OData service running on ASP.NET Core fails with 404 when it shouldn't. Note that this is a different symptom than [this similar issue](https://github.com/OData/WebApi/issues/208), and also likely a different cause since the implementation of CORS in ASP.NET Core is substantially different than the one for classic ASP.NET.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.1

### Reproduce steps

I managed to reproduce this by creating a solution with two projects: One ASP.NET Core Web API project, and one MSTest-based unit test project. For some reason, I couldn't get ASP.NET Core to work at all if I combined all the code in a single project.

The repro is [here](https://github.com/brjohnstmsft/odata-repros/tree/master/ODataAndCors)

### Expected result

All four tests pass

### Actual result

The test that uses CORS with OData fails. The first preflight request returns 404 instead of 200.

### Additional detail

I haven't been able to determine the root cause of this. The failure mode is different than it is in classic ASP.NET.

**Comment by cornem** [comment]
Related to https://github.com/aspnet/CORS/issues/98?

A possible workaround is to let middleware handle the CORS pre-flight requests (but it means less granular control over CORS policies):

	services.AddCors(options =>
	{
		options.AddPolicy(
			"AllowAllOrigins",
			builder => builder
                            .AllowAnyOrigin()
                            .AllowAnyHeader()
                            .AllowAnyMethod()
                            .AllowCredentials());

		options.DefaultPolicyName = "AllowAllOrigins";
	});

And adding `app.UseCors()` before the call to `UseMvc()`.

The [`ODataRequestMethod`](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/RequestMethod.cs) enum doesn't know `Options`, so `Unkown` is returned [here](https://github.com/OData/WebApi/blob/3ec3a69fc557a9f6a0380ee21940c2998c02b394/src/Microsoft.AspNetCore.OData/Adapters/WebApiRequestMessage.cs#L91). As a result [`EntitySetRoutingConvention`](https://github.com/OData/WebApi/blob/3ec3a69fc557a9f6a0380ee21940c2998c02b394/src/Microsoft.AspNet.OData.Shared/Routing/Conventions/EntitySetRoutingConvention.cs#L24) doesn't find a matching action.

I have done a local test where I've set the method to whatever is passed in the `Access-Allow-Control-Method`, and then the result will be `200`. Inserted at [L83](https://github.com/OData/WebApi/blob/3ec3a69fc557a9f6a0380ee21940c2998c02b394/src/Microsoft.AspNetCore.OData/Adapters/WebApiRequestMessage.cs#L82):

	if (method.Equals("OPTIONS", StringComparison.InvariantCultureIgnoreCase) 
		&& innerRequest.Headers.ContainsKey( "Access-Control-Request-Method"))
	{
		method = innerRequest.Headers["Access-Control-Request-Method"]
			.First().ToUpperInvariant();
	}

**Comment by JoshZA** [comment]
👍

**Comment by TehWardy** [comment]
Tell me about it ... 

I wish there was a way I could just say "See that OPTIONS header and just return OK" as CORS is a blight on the internet. 

All it does is force all clients to hit the servers twice since there's literally no way to verify the information in the request is valid it boils  down to trusting the client to tell you they care about this and are giving you the right information. Much like the EU cookie directive ... this feature needs to die!

Rant over ... In the meantime ... 

I would like a way to do something like "app.UseCors().AllowAnything()" and just have any request from any browser accept that all OPTIONS request have come back positive regardless.

Right now the only way I know of to get this behavior is to literally put in custom middle-ware to look for the OPTIONS header and respond then end the request but that's an ugly hack.

**Comment by marabooy** [comment]
Closing this as a it is fixed now.
