### ISSUE TITLE
.net core - change default root node name "value"

### ISSUE THREAD

**Issue by suadev** [OData/WebApi#1838]
How can i change default root name called "value" ? 

I need to replace it with "results".  Is that possible?

```
{
    "@odata.context": "http://localhost:5000/odata/$metadata#rooms",
    "value": [
        {
            "id": "17aa0d64-e475-4481-b383-71de2269a546",
            "no": "107",
            "roomTypeCode": "EXEC",
            "isVirtual": false,
            "roomTypeTranslations": [
                {
                    "culture": "TR",
                    "name": "Executive",
                    "description": null
                }
            ],
            "translations": [
                {
                    "culture": "TR",
                    "name": "EXEC"
                }
            ]
        }
    ]
}
```

**Comment by suadev** [comment]
@robward-ms Any idea?

**Comment by mikepizzo** [comment]
The WebApi OData libraries generate compliant OData payloads, which mandate that the wrapper for the top-level collection object is called "value", so we don't have a direct way to return a non-compliant value.

You could, however, get something similar to the output structure you describe by defining a top-level singleton with a single "results" navigation property of type Collection(rooms). The queries, however, would be slightly different. i.e., instead of 
   GET rooms
you would do 
   GET root?$expand=results 
and instead of 
   GET rooms?$filter=roomTypeCode eq 'EXEC'
you would do something like:
   GET root?$expand=results($filter=roomTypeCode eq 'EXEC')

**Comment by suadev** [comment]
@mikepizzo thank you for detailed explanation. 

I expected to be able to change easily, without using 'expand' keyword, which brings more complexity to all queries :(

**Comment by gathogojr** [comment]
Request by issue reporter to rename top-level property from `value` to `results` cannot be accommodated since that is not supported by the OData protocol specification
