### ISSUE TITLE
Unable to PATCH explicit null value for dynamic property in complex open type

### ISSUE THREAD

**Issue by tinayan328** [OData/WebApi#2070]
The issue is we have an entity type `Item` which includes a complex open type `ComplexOpenType`:
```
public class Item 
{
  public ComplexOpenType ComplexOpenTypeValue { get; set; } 
} 
public class ComplexOpenType 
{ 
  public IDictionary<string, object> Properties { get; set; } 
}
```
And we want to be able to update an existing `Item` instance with some dynamic properties in the `Properties` set to explicit null value.
For example, for a `Delta<Item> delta` and existing `Item item`
```
delta = {
  "ComplexOpenTypeValue": 
  {
    "field": null,
    "field2": "something"
  }
}
item = {
  "ComplexOpenTypeValue": null
}
```
The current result for `delta.Patch(item)` is
```
item = {
  "ComplexOpenTypeValue": 
  {
    "field2": "something"
  }
}
```
The expected result for us is
```
item = {
  "ComplexOpenTypeValue": 
  {
    "field": null,
    "field2": "something"
  }
}
```
In another word, we want to be able to distinguish `null` and `undefined`, is there anything we can do to make it happen?

**Comment by marabooy** [comment]
@tinayan328 This is by design. In dynamic properties null is interpreted as absence of the dynamic property. Setting the dynamic property to null essentially is the interpreted as removing it, maybe in this case you could use a user defined value which will mean its null and then you can utilize the default behavior to mean undefined.

**Comment by xuzhg** [comment]
@tinayan328 Same the comments from @marabooy , This is by design when i implement the dynamic property feature. See the code at: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs#L530

You should assume the value of missing dynamic property after patch is same as the dynamic property with "null" value.

For more detail information, please see http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SetaValuetoNull.

**Comment by tinayan328** [comment]
Thank you for the help. The workaround I have in the end is call `Delta.TryGetPropertyValue("ComplexOpenTypeValue", out object value)` and make a copy of the result `value` before call `Delta.Patch`.
