### ISSUE TITLE
Issue with nested collection nextlink generation when using API versioning

### ISSUE THREAD

**Issue by gregfullman** [OData/WebApi#2321]
When using API versioning with ASP.NET Core OData, and enforcing a PageSize limit to enable server-side paging, the nextlink generation for nested collections throws an exception. This seems to be due to the generated nextlink uri containing a URL encoded character '/' that causes the parsing of the generated uri to fail.

### Assemblies affected

Microsoft.AspNetCore.OData 7.5.0 (also reproduced in master branch)

### Reproduce steps

Reproduced by forking the aspnet-api-versioning repo and modifying one of the samples to enable server-side paging and expansion of a child navigation collection with more records than the server-side page size limit. See commit here: https://github.com/gregfullman/aspnet-api-versioning/commit/04a3b26bb998f9f50e9367319c953d30d49a18ec.

Debugging that sample, go to this url in the browser: http://localhost:5000/v1/People?$expand=orders

### Expected result

The OData response would include the first N child records, along with a {childEntity}@odata.nextLink property, providing the nextlink to retrieve additional child records.

### Actual result

In the case of this sample app, the response displayed in the browser is not complete JSON. An exception will show up in the console output (if you're debugging, an unhandled exception will appear).

![image](https://user-images.githubusercontent.com/2920951/95656470-9c855a00-0adc-11eb-87b4-21764e280073.png)

### Additional detail

The commit I made in this branch fixes the issue: https://github.com/gregfullman/WebApi/commit/330fce017823f8ef3ae3501f349d24e161277eca. It seems that if API versioning is being used, the nextlink generation takes a different codepath that results in the URL encoded forward-slash being included in the nextlink uri.

This commit works with all existing tests, and seems to be sufficiently isolated to the nested navigation collection nextlink use-case I'm dealing with. However, I could use some guidance incorporating existing or new tests to cover this change. I'm happy to submit a PR to incorporate this change as well.

**Comment by gathogojr** [comment]
Hi @gregfullman.
I cloned your repo and switched to _example/nested-nextlink-bug_ branch

![image](https://user-images.githubusercontent.com/28291332/96179266-49c2fc80-0f39-11eb-94ce-05b17ef482db.png)

I then ran the **aspnetcore/ODataBasicSample** project where you made changes to `PeopleController` and no exception was thrown when I tried to expand `Orders`.
```json
{
    "@odata.context": "http://localhost:1238/api/$metadata#People(orders())",
    "value": [
        {
            "id": 1,
            "firstName": "Bill",
            "lastName": "Mei",
            "orders": [
                {
                    "id": 1,
                    "createdDate": "2020-10-15T22:51:52.5645197+03:00",
                    "effectiveDate": "2020-10-15T22:51:52.5645194+03:00",
                    "customer": "Bill"
                },
                {
                    "id": 2,
                    "createdDate": "2020-10-15T22:51:52.5645213+03:00",
                    "effectiveDate": "2020-10-15T22:51:52.5645212+03:00",
                    "customer": "Bill"
                },
                {
                    "id": 3,
                    "createdDate": "2020-10-15T22:51:52.5645217+03:00",
                    "effectiveDate": "2020-10-15T22:51:52.5645216+03:00",
                    "customer": "Bill"
                },
                {
                    "id": 4,
                    "createdDate": "2020-10-15T22:51:52.5645221+03:00",
                    "effectiveDate": "2020-10-15T22:51:52.564522+03:00",
                    "customer": "Bill"
                },
                {
                    "id": 5,
                    "createdDate": "2020-10-15T22:51:52.5645225+03:00",
                    "effectiveDate": "2020-10-15T22:51:52.5645224+03:00",
                    "customer": "Bill"
                }
            ],
            "orders@odata.nextLink": "http://localhost:1238/api/People(1)/orders?$skip=5"
        }
    ]
}
```

Just a few notes that otherwise didn't have any impact on the tests I did while attempting to repro the issue:
- In _Startup.cs_, you're using both the query string and url segment methods to map the versioned routes. I don't think you should be doing that based on [this](https://github.com/microsoft/aspnet-api-versioning/blob/3098017155ebd31e5a3ab1500d9617a00d4c4bf8/samples/aspnetcore/ODataBasicSample/Startup.cs#L40) comment
    ```cs
    routeBuilder.MapVersionedODataRoutes( "odata", "api", models );
    routeBuilder.MapVersionedODataRoutes( "odata-bypath", "v{version:apiVersion}", models );
    ```
- In _PeopleController.cs_, the order with Id 5 is [repeated](https://github.com/gregfullman/aspnet-api-versioning/commit/04a3b26bb998f9f50e9367319c953d30d49a18ec#diff-ab68651e46394a31bbbb6a0d1c86c9fe88c3185b1e884a5a19736bf9bd30169dR66).

However, just to reiterate, expand and generation of `orders@odata.nextLink` worked without making any changes.  

Note also that I created an isolated repro with the release OData Api Versioning packages and everything worked as expected. Please check again and revert.

**Comment by gregfullman** [comment]
@gathogojr what URL did you use to test the response? Based on the response you got back, I'm guessing you ran something like `http://localhost:5000/api/People?api-version=1.0&$expand=orders`, which does seem to work correctly. However, when you specify the API version as part of the route (i.e. `http://localhost:5000/v1/People?$expand=orders`), that's when I see the problem.

**Comment by gathogojr** [comment]
Hi @gregfullman I tried the query string form. I'll test with the segment form and revert
