### ISSUE TITLE
How to create simple action with parameter and add template route

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#2477]
I want to create action with parameter. I am creating action in collection of entity. It is working without parameter, but I want to work it with parameter. I want my action work with this route template: .../OData/Student/{Action}/{Parameter}

### Assemblies affected

Microsoft.AspNetCore.OData 7.5.7

### Reproduce steps

My configuration:

```
        static IEdmModel GetEdmModel()
        {
            var odataBuilder = new ODataConventionModelBuilder();
            var entity = odataBuilder.EntityType<Student>();
            var action = entity.Collection.Action("MyMethod");
            action.Returns<IActionResult>();
            return odataBuilder.GetEdmModel();
        }
```
My action in controller:

```
[HttpPost]
        public IActionResult MyMethod(string parameterName)
        {
            //Do some...
            return Ok();
        }
```

### Expected result
I want my action run in this query:../OData/Student/{Action}/{Parameter}
It is very important my route to be like: ../OData/Student/{Action}/{Parameter}

### Actual result

My action does not hit.

**Comment by habbes** [comment]
Hi @komdil actions get their parameters from the request body, not from the URL path. The url that you have shared is not valid for OData actions. If it's very important to have a the parameter in the URL, then consider using a function instead of an action and use a `GET` request.

If you intended to use an action, this is how you would set up your model and controller. If you bind the action to a collection, you should ideally create an entity set for the `Student` entity type.  So your model should look like:
```c#
static IEdmModel GetEdmModel()
{
    var odataBuilder = new ODataConventionModelBuilder();
    var entitySet = odataBuilder.EntitySet<Student>("Students");
    var entity = odataBuilder.EntityType<Student>();
    var action = entity.Collection.Action("MyMethod");
    action.Parameter<int>("parameterName");
    action.Returns<IActionResult>();
    return odataBuilder.GetEdmModel();
}
```

```c#
[HttpPost]
public IActionResult MyMethod([FromBody] ODataActionParameters parameters)
{
    parameters.TryGetValue("parameterName", out object value);
    return Ok($"param value is {value}");
}
```

And the request body would look like:
```json
{  "parameterName": 10 }
```

For more information, see: https://docs.microsoft.com/en-us/odata/webapi/action-parameter-support

**Comment by komdil** [comment]
> Hi @komdil actions get their parameters from the request body, not from the URL path. The url that you have shared is not valid for OData actions. If it's very important to have a the parameter in the URL, then consider using a function instead of an action and use a `GET` request.
> 
> If you intended to use an action, this is how you would set up your model and controller. If you bind the action to a collection, you should ideally create an entity set for the `Student` entity type. So your model should look like:
> 
> ```cs
> static IEdmModel GetEdmModel()
> {
>     var odataBuilder = new ODataConventionModelBuilder();
>     var entitySet = odataBuilder.EntitySet<Student>("Students");
>     var entity = odataBuilder.EntityType<Student>();
>     var action = entity.Collection.Action("MyMethod");
>     action.Parameter<int>("parameterName");
>     action.Returns<IActionResult>();
>     return odataBuilder.GetEdmModel();
> }
> ```
> 
> ```cs
> [HttpPost]
> public IActionResult MyMethod([FromBody] ODataActionParameters parameters)
> {
>     parameters.TryGetValue("parameterName", out object value);
>     return Ok($"param value is {value}");
> }
> ```
> 
> And the request body would look like:
> 
> ```json
> {  "parameterName": 10 }
> ```
> 
> For more information, see: https://docs.microsoft.com/en-us/odata/webapi/action-parameter-support

Can you show it with function? I cannot put parameter in body. I want my action/function run in this query:../OData/Student/{Action}/{Parameter}
It is very important my route to be like: ../OData/Student/{Action}/{Parameter}

**Comment by komdil** [comment]
Why this market as Closed???? I didn't get any solution

**Comment by habbes** [comment]
Hi @komdil the issue had been closed due not receiving a response. Apologies for the misunderstanding.

Could you share more information about what you're trying to achieve? Could you also share the odata model that you're service is based on?

OData provides 2 mechanisms for calling custom procedures: actions and functions.

Actions are intended for procedures that have side-effects (e.g. they modify data in your system). Actions use POST HTTP method and the parameters are accepted via the request body.

Functions are normally used for procedures that have no side-effects. They use a GET request and can accept parameters in the path. However, the syntax for accepting function parameters is through parentheses, i.e. `odata/Students/Function({parameter})` rather than `odata/Students/Function/{parameter}`

**Comment by komdil** [comment]
@habbes  I already provided my model. I am trying to join one service to my OData service. It required this template:  odata/Students/Function/{parameter}
Is it possible to this?

**Comment by habbes** [comment]
@komdil I don't know if the URL you want is supported for functions. If you want to pass a parameter to a function, you'd use the following syntax: `odata/Students/Function(param=10)` (i.e. you pass the parameter name and value in parantheses. I don't think OData allows you to pass function parameters after a slash. That is only supported when providing keys of entities or navigation properties (e.g.: `odata/Students/1/Courses/2`).

If you're okay with passing parameters in parantheses, then  you can use a function. Furthermore, you should create an `Students` entity set in your model. Your model could be define as follows:
```c#
var entitySet = odataBuilder.EntitySet<Student>("Students");
var entityType = odataBuilder.EntityType<Student>();
var function = entityType.Collection.Function("MyFunction");
function.Parameter<int>("param");
function.Returns<string>();
// ...
```
Note that the function in the model is set configured to return a `string` and not an `IActionResult`

And in your `StudentsController`  add the method:
```c#
public IActionResult MyFunction(int param) {
    return Ok($"param value is {param}");
}
```
And you could send the request: `GET odata/Students/Function(param=10)`.

If you do not want parantheses in the URL for the parameter. Then maybe you could consider using a non-OData route to handle that request. In this case the controller action could use the AspNetCore `[Route]` attribute for routing, it does not need you to define the function in the OData model. This route is not handled by OData:
```c#
[Route(Students/MyFunction/{param}]`
public IActionResult MyFunction(int param) {
    return Ok($"param value is {param}");
}
```

Let me know if any of these suggestions work for you.

**Comment by habbes** [comment]
@komdil I'm closing the issue due to inactivity. Feel free to re-open the issue if the above suggestions do not solve your issue. Thanks.
