### ISSUE TITLE
AmbiguousMatchException for properties with new modifier (Fixed in OData/AspNetCoreOData)

### ISSUE THREAD

**Issue by Aarabika** [OData/WebApi#2516]
This line throw AmbiguousMatchException 

https://github.com/OData/WebApi/blob/757631faf10b494e55117904196e8aa45d4c764d/src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs#L178

**Case** 
```
public class RequestReply
{
        public Guid Id { get; set; }
}

public class ChildRequestReply : RequestReply
{
        public Guid Id { get; set; }
}

public class Request
{
        public Guid Id { get; set; }
        public ICollection<RequestReply> Replies { get; set; }
}

// odata serializer will throw exception
public class ChildRequest : Request
{
        public Guid Id { get; set; }
        public new ICollection<ChildRequestReply> Replies { get; set; }
}
```

Fixed in https://github.com/OData/AspNetCoreOData/pull/203, any opportunities to fix this there and add to 7.x release?

**Comment by habbes** [comment]
Hi @Aarabika thanks for reporting this. I see that you're the one who fixed the issue in 8.x. Would you be willing to port the fix to this version as well? We'll be happy to review your PR.

**Comment by habbes** [comment]
@Aarabika regarding [the fix that you provided in 8.x](https://github.com/OData/AspNetCoreOData/pull/203/files#diff-f80bb1a01968c0256936bad0b2feb0f3376c194be2466793d5c7d1e5d71905e2R173), there's some concern on whether we can rely on `GetProperties(p => p.Name == propertyName).First()` always returning the current class's implementation and not the base class's (assuming both properties are returned by` GetProperties()`). You mention in your PR description that the first property in a collection is always from the current class (i.e. the one the `Type` object refers to) and not the base class. Is this behavior guaranteed?

The [official documentation of the method](https://docs.microsoft.com/en-us/dotnet/api/system.type.getproperties?view=net-5.0#System_Type_GetProperties) states the following

> The [GetProperties](https://docs.microsoft.com/en-us/dotnet/api/system.type.getproperties) method does not return properties in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which properties are returned, because that order varies.

It doesn't mention inheritance hierarchy explicitly, and it seems reasonable to expect methods declared on the type to appear before those hidden in base types, but this might just be an implementation detail. Are you able to point to any documentation that guarantees that the current type's property is listed first?

The [documentation for the GetProperty(string name)](https://docs.microsoft.com/en-us/dotnet/api/system.type.getproperty?view=net-5.0#System_Type_GetProperty_System_String_) overload mentions that the `AmbiguousMethodException` can occur when using the `new` modifier on the child class (which is the situation we're facing). But it proposes to resolve that ambiguity by calling [GetProperty(string, BindingFlags)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.ireflect.getproperty?view=net-5.0#system-reflection-ireflect-getproperty(system-string-system-reflection-bindingflags)) and passing the `BindingFlags.DeclaredOnly` to restrict the search to properties declared directly on the class and exclude inherited ones.

Obviously that solution would also be problematic because we do want to be able to get inherited properties when they are not shadowed by a separate child class implementation.

Furthermore, in consider a situation like the following:
```c#
class A
{
    public string Prop { get; set; }
}

class B : A
{
    public new int Prop { get; set; }
}

class C : B
{
}
```
In this case if you're writing an entity of type C, you want to resolve to `Prop` defined in B.

I think we should not rely on the assumption that `GetProperties()` return inherited properties in any particular order unless there's explicit documentation that guarantees it. If you've come across such documentation, could you point to it?

Otherwise, I think we should find a workaround that does not assume any order. For example, we can call `GetProperty(string name)` with `BindingFlags.DeclaredOnly` and if that returns `null`, then we call `GetProperty(string name)`.

**Comment by gathogojr** [comment]
My proposal would be for something like this:
```csharp
public class A
{
    public string Prop { get; set; }
}

public class B : A
{
    public new int Prop { get; set; }
}

public class C : B
{
}

public interface D
{
    string Prop { get; set; }
}

public class E : D
{
    // `new` can't be used to hide properties where interfaces are involved
    public string Prop { get; set; }
}

private static PropertyInfo GetProperty(Type targetType, string propertyName)
{
    PropertyInfo[] properties = targetType.GetProperties().Where(d => d.Name.Equals(propertyName)).ToArray();

    if (properties.Length == 0)
    {
        return null;
    }
    if (properties.Length == 1)
    {
        return properties[0];
    }
    else
    {
        Type declaringType = targetType;
        PropertyInfo propInfo = null;

        do
        {
            // We would never expect declaring type to be null
            Contract.Assert(declaringType != null, $"Declaring type for {propertyName} property not expected to be null");

            propInfo = properties.FirstOrDefault(d => d.DeclaringType.Equals(declaringType));
            declaringType = declaringType.BaseType;
        }
        while (propInfo == null);

        return propInfo;
    }
}


// To verify behaviour
var cProperty = GetProperty(typeof(C), "Prop");
Debug.Assert(cProperty.PropertyType == typeof(int));

var bProperty = GetProperty(typeof(B), "Prop");
Debug.Assert(bProperty.PropertyType == typeof(int));

var aProperty = GetProperty(typeof(A), "Prop");
Debug.Assert(aProperty.PropertyType == typeof(string));

var dProperty = GetProperty(typeof(D), "Prop");
Debug.Assert(dProperty.PropertyType == typeof(string));

var eProperty = GetProperty(typeof(E), "Prop");
Debug.Assert(eProperty.PropertyType == typeof(string));
```

**Comment by Aarabika** [comment]
@habbes Thanks for comments, fixed in odata 8.x mr - https://github.com/OData/AspNetCoreOData/pull/226

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/WebApi/pull/2523
