### ISSUE TITLE
Question: Difference between src/Microsoft.AspNetCore.OData and AspNetCoreOData

### ISSUE THREAD

**Issue by ificator** [OData/WebApi#2651]
I noticed that there's a new `AspNetCoreOData` repository that seems to be the, well, AspNetCore version of the `OData` library. But there's also the `src/Microsoft.AspNetCore.OData` directory in this repository. Is the AspNetCore code in this repository no longer used? If so, it would be good to remove it to avoid confusion.

Also, as the two code bases divergence what is the expectation for bug fixes etc done here? Should we be creating PRs in the new repo as well or will that be handled by the team?

**Comment by xuzhg** [comment]
@ificator 

- https://github.com/OData/WebApi is a repository for ASP.NET (Core) OData 7.x, meanwhile, 
- https://github.com/OData/AspNetCoreOData is a repository for ASP.NET Core OData 8.x.

ASP.NET (Core) OData 7.x:
1) Includes OData on ASP.NET Classic (.Net Framework) and OData on ASP.NET Core
2) The namespace is 'Microsoft.AspNet.OData' for both
3) Contains model builder as component in the project

ASP.NET Core OData 8.x repository:
1) Only includes ASP.NET Core 
2) namespace is "Microsoft.AspNetCore.OData"
3) separate the model builder into an individual library.

ASP.NET (Core) OData 8.x and ASP.NET (Core) OData 7.x have different routing, different namespace, different model builder. If you are building your service on 8.x, please file issues on https://github.com/OData/AspNetCoreOData, Otherwise, please file issue in this repository. 

Hope it can clarify the confusing.
