### ISSUE TITLE
Web API OData Specification Issues

### ISSUE THREAD

**Issue by Vaccano** [OData/WebApi#279]
We are currently trying to setup a web development stack.

What we were looking at has us using Web API OData and BreezeJS.

However, BreezeJS is saying that the Web API OData implementation does not follow the specification in several key places.  **Making saving to more than one table a matter of luck and navigating foreign keys impossible.**

Here are the links to this information:

http://www.getbreezenow.com/documentation/odata-server
http://www.getbreezenow.com/documentation/odata-vs-webapi

Quotes like this from the page have me worried:

>Microsoft has promised to repair the deficiencies but has not done so yet and has no timetable for doing so. After almost a year of waiting we have grown pessimistic.

I am worried about basic missing functionality like these articles indicate.  Especially when this project seems to be spending so much time on things like disabling DateTime and then creating workarounds for it.

I know you feel you need to follow the spec, but surely some parts of it are more important than others?

I hope that I will get a response that says that the BreezeJS documentation is out of date and that you have already fixed all these issues!  If so, please let me know.

**Comment by xuzhg** [comment]
We are sorry about this, however OData team works hard to fix the gap. Some parts in BreezeJS documentation is truth, but most of them are really out of date. For example, the doc mentions that:
`6.OData does not support .NET enum types.`
This is not truth. Since Web API OData 5.1, .NET enum type has been supported.

We are happy to help you solve your concrete OData problem and glad to hear your feedback. Thanks.

Please re-open it if you have more concern.

**Comment by Vaccano** [comment]
Enum support is the very least of the issues that page mentions. 

The biggest are lack of batching support and inability to commit in the right order. 

What is the status of those?

**Comment by congysu** [comment]
@Vaccano The issue is tracked in https://github.com/OData/WebApi/issues/309.  OData Web API [5.4](http://odata.github.io/WebApi/5.4/) has done the following:
* Referential constraint (v4, v3) #37
* Case-insensitive support (v4) #11
* StoreGeneratedPattern annotation (v3) #189
* ConcurrencyMode annotation and ETag (v3) #190
