### ISSUE TITLE
GeneateActionLink should apply lowercase for bindingParameterType

### ISSUE THREAD

**Issue by vasrinwork** [OData/WebApi#2810]
Currently, while generating an action link for an odata action, the LinkGenerationHelpers.GenerateActionLink method looks for a parameter type which does not match the ones in the IEdmModel.
This is because the method uses the bindingParameter.Type parameter which does not enforce lowercase, however the model schema elements are lowercased.
The solution would be to replace the Type with the fullName parameter.

### Assemblies affected

AspNet.OData lib 7x

### Reproduce steps

Consider an action called simpleAction, which is applied on a type 'Plan' with namespace microsoft.simple.plan,
```
ActionConfiguration simpleAction= builder.EntitySet<Plan>("plan").EntityType
    .Action("simpleAction");
```
Here, the model contains the declared type "microsoft.simple.plan" and the bindingParameter's type shows "microsoft.simple.Plan".
this results in a mismatch and a NullReferenceException.

### Expected result
The result should return a link generated for actions
```
"#microsoft.simple.simpleAction": {
        "title": "simpleAction",
        "target": "http://localhost/V3.0/plans('lsPtJMLRzUyfE12cVfCv-f8ABBP1')/microsoft.simple.simpleAction"
      }
```

### Actual result

System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by xuzhg** [comment]
The customer has the following logic:
```C#
var builder = new ODataConventionModelBuilder();
builder.OnModelCreating += ApplyLowerCamelCase;
```
Where 'ApplyLowerCamelCase' is used to change the type and property name (camel case).

It looks like `OnModelCreating` is misused here, since 'This action is invoked after the ODataConventionModelBuilder has run all the conventions.`

It means model builder runs all conventions before calling 'OnModelCreating'. 

There's conventions to build action/function links, the link builder takes the type name before 'OnModelCreating' logic change it. So, the link builder uses the 'original' type name (it's 'Plan'). Meanwhile, 'OnModelCreating' changes the type name using camel case (it's 'plan').  So, the link builder can not find the edm type using the 'original' type name since the edm model only contains camel case type name.

Customers should understand the usage of 'OnModelCreating' (avoid changing the type name within it, etc). On our side, 
We can resolve it by simply using 'ignoreCase' to look up the type.
