### ISSUE TITLE
NU1608: Detected package version outside of dependency constraint: Microsoft.AspNet.WebApi.OData 5.7.0 requires Microsoft.AspNet.WebApi.Core (>= 5.2.2 && < 5.3.0) but version Microsoft.AspNet.WebApi.Core 5.3.0 was resolved.

### ISSUE THREAD

**Issue by robinvanpoppel** [OData/WebApi#2814]
`Microsoft.AspNet.OData` has a dependency on [Microsoft.AspNet.WebApi.Core](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Core/) (>= 5.2.2 && < 5.3.0). Recently version 5.3.0 of that dependency was released which falls just outside the range. I am not fully familiar with the versioning strategy, but I guess this constraint could be relaxed a little.

### Assemblies affected

Microsoft.AspNet.OData 7.7.2

### Reproduce steps

* Add a reference to `Microsoft.AspNet.OData` 7.7.2
* Add a reference to `Microsoft.AspNet.WebApi.Owin` 5.3.0 / `Microsoft.AspNet.WebApi.Core`

### Expected result

Newer version of a nuget which allows a higher version of Microsoft.AspNet.WebApi.Core

### Actual result

`NU1608: Detected package version outside of dependency constraint: Microsoft.AspNet.WebApi.OData 5.7.0 requires Microsoft.AspNet.WebApi.Core (>= 5.2.2 && < 5.3.0) but version Microsoft.AspNet.WebApi.Core 5.3.0 was resolved.`

### Additional detail

[AspNetPackageDependency](https://github.com/OData/WebApi/blob/7136f995c9a680698a2a0f3c37a6ffe499369479/tools/WebStack.versions.settings.targets#L14) describes the version range.

**Comment by corranrogue9** [comment]
@robinvanpoppel in the issue title, you refer to `Microsoft.AspNet.WebApi.OData 5.7.0`, but in the description you refer to `Microsoft.AspNet.OData 7.7.2`. `5.7.0` is out of support, but for `7.x`, we will update our nuspec to allow `5.3.0` and then update our dependency as well. We will ensure that there are no breaks in doing so. If you are using `5.7.0`, you will need to update to `7.x` take this change when we have released; if you are able to use ASP.NET *Core*, you should probably update to `8.x` instead though, since you will encounter breaking changes upgrading to `7.x` anyway.

**Comment by robinvanpoppel** [comment]
@chrisspre Sorry for the confusion. Amidst figuring out what was going on I already swapped `Microsoft.AspNet.WebApi.OData` with `Microsoft.AspNet.OData`. I created the issue with the original package error because that was my starting ppint. Good to hear that you're planning to update the dependency for v7 so we will swap to that when it ships. Thanks a lot!
