### ISSUE TITLE
Null-valued open properties not getting serialized

### ISSUE THREAD

**Issue by MaxWilson** [OData/WebApi#312]
Description:

Open properties with null values are omitted from serialized output. Makes it impossible to distinguish unset open properties from properties set to null.

Minimal repro steps:
Create an open type. Make a service operation which returns an instance of that open type, with its dynamic property collection set to new Dictionary<string, object> { { "MyNullProperty", null } }. Call the service operation. Property will not be there.

Example (only NonNullProperty shows up in output):
        // GET: odata/Stores
        [EnableQuery]
        public IQueryable<Store> GetStores()
        {
            var retval = new Store
            {
                StoreID = 8,
                StoreName = "My store",
                DynamicProperties = new Dictionary<string, object> { { "MyNullProperty", null }, { "MyNonNullProperty", 42 } }
            };
            return new[] { retval }.AsQueryable();
        }

Expected result: 
Null properties become ODataNull type.

Actual result:
ODataEdmTypeSerializer.AppendDynamicProperties() skips over null-valued properties as if they don't exist. Output in screenshot:

![image](https://cloud.githubusercontent.com/assets/6829565/7235463/333b9022-e743-11e4-9f04-f7b6298242ee.png)

Further technical details:
As best I can tell, the OData spec does not restrict the values of open properties, so it should be possible to have null-valued open properties.

**Comment by MaxWilson** [comment]
Sorry, paste error excluded type parameters. Corrected:

        // GET: odata/Stores
        [EnableQuery]
        public IQueryable GetStores()
        {
            var retval = new Store
            {
                StoreID = 8,
                StoreName = "My store",
                DynamicProperties = new Dictionary<string, object> { { "MyNullProperty", null }, { "MyNonNullProperty", 42 } }
            };
            return new[] { retval }.AsQueryable();
        }

**Comment by congysu** [comment]
Thanks @MaxWilson for reporting the issue.  Please feel free to submit a pull request on it.

**Comment by xuzhg** [comment]
@MaxWilson Skip the null dynamic property to serialize is by design. What's your scenario to have a null-dynamic property in the payload?

I do think you can set the value as null if you can't find the dynamic property in the payload. Please let us know your thought. thanks.

**Comment by MaxWilsonMS** [comment]
Scenario is letting end-users have a property bag for business data that actually shows everything that's in the bag (so that adding new properties doesn't take a dev cycle). Also, the fact that the OData spec says that open properties can be nullable, so I should think the scenario is also "implement behavior from the OData spec."

It's hard to be more specific about the scenario because OData scenarios are always kind of loose, but I'll talk to my PM and try to get a concrete scenario for you where null and missing are different things.

**Comment by xuzhg** [comment]
@MaxWilson please re-open it if you have further concern. Thanks.

**Comment by michalhainc** [comment]
I also have a scenario where a global OData action is returning tree structure of objects of various types, I use wrapper open type with dynamic properties to represent these variously typed objects and reflexively read properties from those objects into dynamic properties dictionary, now properties that are null are not serialized which is a disaster for the client, because the client does not know which properties to expect in which node of the tree serialized in the response. 

I think a possibility to force serialization of dynamic properties would is needed in many valid cases and is not against the OData standard.

**Comment by michalhainc** [comment]
So after half day of digging found the solution by decompiling System.Web.OData

`config.Properties.AddOrUpdate("System.Web.OData.NullDynamicPropertyKey", val=>true, (oldVal,newVal)=>true);`
