### ISSUE TITLE
allow support for odata $metadata formats

### ISSUE THREAD

**Issue by grahamehorner** [OData/WebApi#432]
the odata framework should allow extensions to the $metadata route to allow the support of other types of metadata formats; ie: support the JayData format via ../odata/$jaydata ../odata/$metadata?format=jaydata and/or via the http header accepts attribute.

**Comment by congysu** [comment]
Related issue: https://github.com/OData/WebApi/issues/302

**Comment by mikepizzo** [comment]
We have added support for swagger format, but note that the swagger is not isomorphic with the xml CSDL representation. In particular, swagger/json schema are unable to represent many fundamental data model concepts that are represented in the XML CSDL representation. Note that OASIS has added a JSON format of CSDL that is isomorphic with the XML CSDL representation and fully describes the underlying model.  We will likely see a work item to add support for that JSON CSDL representation in the near future.

**Comment by mikepizzo** [comment]
As noted above, we have added support for swagger/json schema, not as a $metadata response format, but through other mechanisms. We also expect to add support for a JSON CSDL representation.

Support for other service descriptions can be handled similarly to swagger/json; rather than specifying a different type for $format, other endpoints can be added to service specific descriptions.

Closing this issue, as per [triage guidelines](https://github.com/OData/WebApi/blob/master/.github/ISSUE_TRIAGE.md). Feel free to reopen the issue if you feel it is still valid and you believe it will have broader user impact. Without support from additional users, however, you should not expect to see a higher priority assigned to the issue.

You are always welcome to assign this issue to yourself and submit a pull request with the necessary changes. See our contribution guidelines for further information.

Thank you for your continued interest in the OData libraries.
