### ISSUE TITLE
A way around MultipleActiveResultSets (MARS)

### ISSUE THREAD

**Issue by esditm** [OData/WebApi#536]
I'm using a MySql db. MySql doesn't support MARS :(

I need to execute a fairly complex query on my OData endpoint which relies on MARS. At least it throws this exception:

> message: There is already an open DataReader associated with this Connection which must be closed first.
> type: MySql.Data.MySqlClient.MySqlException

So I was wondering if there was a way to turn MARS off in OData. If not then it's a feature request :)

**Comment by VikingsFan** [comment]
@esditm Did you check [this](http://stackoverflow.com/questions/20693216/there-is-already-an-open-datareader-associated-with-this-connection-which-must-b) out? 

This problem is that there are multiple data retrieval commands executed on single connection (or single command with multiple selects) while next DataReader is executed before first one has completed the reading, OData didn't handle these logics by now.

**Comment by VikingsFan** [comment]
Please reopen it when you have any concern.

**Comment by snebjorn** [comment]
As far as I can tell the only way around "already an open DataReader" is to use `.Include(...)`.
But since users can expand any navigation property, I cannot "prepare" the query.

I was looking through your code to see if I could make it do an `.Include` when there was an $expand or `AutoExpand` property.

I found this in `System.Web.OData.Query.Expressions.SelectExpandBinder`

```csharp
private Expression BuildPropertyContainer(IEdmEntityType elementType, Expression source,
    Dictionary<IEdmNavigationProperty, ExpandedNavigationSelectItem> propertiesToExpand,
    ISet<IEdmStructuralProperty> propertiesToInclude, ISet<IEdmStructuralProperty> autoSelectedProperties, bool isSelectingOpenTypeSegments)
{
    IList<NamedPropertyExpression> includedProperties = new List<NamedPropertyExpression>();

    foreach (KeyValuePair<IEdmNavigationProperty, ExpandedNavigationSelectItem> kvp in propertiesToExpand)
    {
```
If this actually adds the `.Include` to the query I couldn't tell. But at least it does something similar.
Am I on the right path?
