### ISSUE TITLE
OData v4.0 non-compliant behavior when the request header contains "odata.streaming=true" and the service does not support streaming

### ISSUE THREAD

**Issue by titanski** [OData/WebApi#608]
Hello,

We have a WebAPI service in production. 

The QA was validating the service's compliance with the Odata version 4.0 spec and have found a non-compliance with the following section.

Section 4.4 of the spec :

http://docs.oasis-open.org/odata/odata-json-format/v4.0/cs01/odata-json-format-v4.0-cs01.html#_Toc365464683

Specifies the following rule :

"Services MUST return 406 Not Acceptable if the client only requests streaming and the service does not support it"

Our service doesn't support any streaming capabilities.

Upon calling the service with the specified payload(for example) as following:

https://URL/SpecificData/.../...

Content-Type: application/json;odata.metadata=minimal;odata.streaming=true

Instead of getting a 406 error, the value in the header is ignored and the JSON- formatted data is returned with a 200 status.

My question is : Should the above described non-compliance with the Odata 4.0 spec be implemented as part of the WebAPI framework?

Or it is the responsibility of  every service developer to implement the logic that will return the 406 error in the described scenario , as part of the service logic.

Thanks,

MG

**Comment by VikingsFan** [comment]
@titanski server should implement the logic to return 406 error if it doesn't support stream.

**Comment by mikepizzo** [comment]
@titanski: When you say "Our service doesn't support any streaming capabilities.", do you mean that your service doesn't support stream properties, or that it doesn't support a default ordering of properties within a JSON payload?

Note that odata.streaming=true just means that you follow certain ordering constraints in the JSON properties you write (for example, context, type, and id control properties come before model properties).  The JSON format says that the order of properties is insignificant, so a client can't necessarily depend on this control information coming before model properties.  The format parameter is a way to specify that, in this JSON format, the control information follows those constraints, allowing the client to read the response in a streaming fashion, rather than having to buffer properties in order to see if an object has context, type, id, or other information.

The OData libraries follow these constraints by default, so if you are using the odata libraries you probably are supporting the ordering constraints, so @odata.streaming is true in your responses.

Perhaps we could have picked a better name than "streaming" to describe this behavior, but it's unlikely to be worth changing at this point.
