### ISSUE TITLE
Nuget package OData v1-3 no longer up to date

### ISSUE THREAD

**Issue by janvanderhaegen** [OData/WebApi#631]
[The nuget package for OData v1-3](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData/) is no longer kept up to date
Last nuget package published was 5.7 (missing 5.8 at moment of writing).

Also, release documentation does not mention this nuget package anymore.

Why would the sources still be maintained if no binaries are distributed?

**Comment by xuzhg** [comment]
@janvanderhaegen

There's no feature added or bug fixed in OData V1-3 since V5.7. 
However, If there's a serial bug or an emergency feature requirement for OData V1-3, ODataTeam will put high priority to finish it and release new package. 

Does the current package meet your development requirement? Do you have any concern for it? 

Please let us know and we'd happy to help you resolve any OData related problem. Thanks.

**Comment by janvanderhaegen** [comment]
Hey @xuzhg 
Actually, I thought the sources for v1-3 and v4 use a set of common classes? If so, any fix in v4 lately which has an impact on those classes should lead to a better v1-3, right?

My team's running into  #630, which I reported for v4 but is also a bug in v1-3, hope to find the time to submit a PR later this week. 

Thanks

J

**Comment by xuzhg** [comment]
Close it. please re-open it if you have further concern.
