### ISSUE TITLE
How to intercept the query and change some query properties?

### ISSUE THREAD

**Issue by EricSch** [OData/WebApi#638]
For example, we are sending some additional filters. When the fields aren't in the returned entity, there is an validation error. But we need the additional query filters to build our own query.

I tried to overwrite the FilterQueryValidator, but the FilterClause is already evaluated (Why?? The parser should only parse them, not validated).

Thanks

**Comment by VikingsFan** [comment]
@EricSch the error should happen in Odata Lib, when parsing filter=UndefinedProperty, it is by design to detect the invalid query option, relative code https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Binders/EndPathBinder.cs#L107-L118 , maybe you can give us a PR for OData Lib, relative Issue : https://github.com/OData/odata.net/issues/375

**Comment by VikingsFan** [comment]
Close as two weeks no-reply
