### ISSUE TITLE
Atom-Support in Odata V4

### ISSUE THREAD

**Issue by phillipc** [OData/WebApi#639]
Wenn I upgrading my odata v3 web api to the odata v4 libraries, the service always return json results. 
For testing, I have forcing atom+xml results without positiv results

`Request.Headers.Add("Accept", "application/atom+xml");`

Old v3 libraries: https://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData/5.7.0
New v4 libraries: https://www.nuget.org/packages/Microsoft.AspNet.OData/5.8.0

Is the atom-support broken or deprecated in v4? I think is a necessary feature to connect microsoft excel with a odata-feed.

**Comment by xuzhg** [comment]
@phillipc 

So far, Atom is still in committee specification, not in OASIS OData standard, see [here](http://www.odata.org/documentation/). OData V4 libraries and the related Web API OData libraries follow up the OASIS standard. Therefore, Atom is temporal removed from libs. 
Once the Atom becomes the part of the standard, OData team will add the support in libs ASAP. Thanks.

**Comment by xuzhg** [comment]
Close it. Thanks.

**Comment by Vicnat35** [comment]
OdataLib 7.00 and Atom support in web Api 2.00, for Office 2013 ...

[Issue #510] Remove Atom support

Atom is still "committed" in Oasis specs, since 2013 and Odata V4 ...
When will it be approved ( 2018 , never ...) ?
We need this to avoid access from Office ( Excel, PowerQuery ...) to ours Data ... :(
It seem's to be ok for Power BI

Thank's
