### ISSUE TITLE
Flattened Results

### ISSUE THREAD

**Issue by Jogai** [OData/WebApi#694]
I found a document by @mikepizzo that says:

> In OData V4, it's possible to request a flattened result. Flattened results are a special type of heterogeneous result in which the result represents a flatten graph (so the root is known). Clients may request, and know how to interpret, flattened results through a content-type parameter.
### Content-Type for Flat Results
The Content-Type for a result representing a flattened hierarchy includes the odata.flat parameter; e.g., application/atom;odata.flat or application/json;odata.flat. 

Is this implemented? And is this part of the spec?
Its only mentioned in 2 documents (see https://www.google.nl/search?q=%22odata.flat+parameter%22)

**Comment by xuzhg** [comment]
@Jogai 

I asked @mikepizzo and got information form him about the flattened result feature. It seems the committee has discussed it years ago because it looks an interesting feature, however it was never formally adopted as part of the odata specification.

Do you want to use this feature in your project? Can you share us more what you want? Thanks.

**Comment by Jogai** [comment]
Thanks for your answer.

I was using the grid from syncfusion which has column autogeneration : http://help.syncfusion.com/js/grid/columns#auto-generation
That feature does work best (or is more easy to use) on flat results, but I managed to make a workaround for that: http://www.syncfusion.com/forums/123647/odata-v4-generated-query-variant. 

Aside from above implementation issues it seems to me that a flatten option is useful in other scenarios as well. A flat result set is easier to work with (or at least I think so, but that could be because of the gaps in my js skills in this case) and when building on top of an api its often useful to show higher level results with aggregated data. By encouraging to flatten the result via the odata query the api can be queried more efficient since the api returns only the fields that are included in the flattened result.  Both points are especially applicable to odata api's I think. When providing odata access its unknown how consumers will use them, and if it gets used more often the efficiency is an important factor for both provider and consumer. 

Feel free to close this issue because my question is answered. If this gets implemented I'm sure I will use it, but I imagine this will take a while.

**Comment by m-rakic** [comment]
I know that issue is closed but is not answered if will be implemented and when aproximatly ;)...  The flattening is coming from database views and from excel. People is exporting it and make reports, data validation... The problem with flattening is not in small data sets because we can flatten nested data in client and fill grid. The problem is with big sets when you wonna get data in chunks but flatten chunks... Not nested and after expanded... Tipical example is database view... Is flatten and chunks is always on flatten result...  hope helps...Thanks for all effort you did great job :)
