### ISSUE TITLE
Delta<Entity> is Null in Patch/Put Actions

### ISSUE THREAD

**Issue by ayleen** [OData/WebApi#699]
If add return-object function like this:
"entity.EntityType.Collection.Function("UpdateSizeCharts").Returns<object>();"
Delta<Entity> in Patch/Put actions in every controller will be null.

**Comment by xuzhg** [comment]
Would you please share us more detail information?

**Comment by Jithinkraju** [comment]
One of Microsoft's customer's was running into a similar issue and then we suggested to implement the fix suggested at https://github.com/xuzhg/WebApiSample/tree/master/WebApiODataSample/WebApiODataSample

Now we are running into another issue, while using createRef(), if we give relative path in request body, URI comes as null. However, if we give full path, everything works as expected

![1](https://cloud.githubusercontent.com/assets/18664953/14793078/044ae304-0b3b-11e6-97a1-3f1d14d4d927.jpg)
![2](https://cloud.githubusercontent.com/assets/18664953/14793080/0740754c-0b3b-11e6-8b75-83cb1ae11217.jpg)

Any comments or pointers on this please?

Best Regards
 Jithin

**Comment by xuzhg** [comment]
Hi, @Jithinkraju

The link payload should be one of the below content:

1. Absolute URIs, or
2. relative URIs, but **"@odata.context" annotation must be on the payload**.

So, as an example;

If the link value only has the relative Uri as below, it will be failed and the `link` parameter in the action `CreateRef` is `null`.
`
{"@odata.id":"Orders(2)"}
`

Otherwise, if the payload is as below:

` {"@odata.context":"http://localhost/odata/$metadata","@odata.id":"Orders(2)"}`

It should be successful. Hope it can help you.

**Comment by Jithinkraju** [comment]
Thank you Sam ☺

Best Regards,

Jithin Raju

[Description: 6076]

**Comment by xuzhg** [comment]
@ayleen

I close this issue. If you still have the problem, please re-open it and provide us the repos. Thanks your input.
