### ISSUE TITLE
V6 No non-OData Http route Registered

### ISSUE THREAD

**Issue by JohnGalt1717** [OData/WebApi#816]
Hi there, 

I upgraded our solution from 5.9.1 to 6.0.0 and had to remove enum prefixing method because it's apparently gone.

But worse I now get this error: "No non-OData Http route Registered" on every query that returns IQueryable. These used to work fine and optionally will have odata parameters on the query but often won't.

How do I fix this?

**Comment by rwmcdonald** [comment]
I too am getting this error, not sure what to do about it.

**Comment by VikingsFan** [comment]
@JohnGalt1717  about enum prefix, can you refer to this V6 end-to-end test : https://github.com/OData/WebApi/blob/OData60/OData/test/E2ETest/WebStack.QA.Test.OData/UriParserExtension/EnumPrefixFreeTest.cs

About the second question, do you mean you are using http route? then you should try this method : configuration.EnableDependencyInjection()

**Comment by rwmcdonald** [comment]
I can't seem to make my runtime model creation work in v6.

I am following the sample here:

It consists of these steps.

The steps are:
1. Create a customized ODataPathRouteConstraint, which allows to set EdmModel property, before Match is called.
2. Create a customized ODataRoute to override GetVirtualPath logic, and generate OData links correctly.
3. Create a customized MapODataServiceRoute that takes a Func<HttpRequestMessage, IEdmModel> instead of an IEdmModel.

I think the problem is in Match I no longer can set the model on Request.ODataProperties

`public override bool Match(
			HttpRequestMessage request,
			IHttpRoute route,
			string parameterName,
			IDictionary<string, object> values,
			HttpRouteDirection routeDirection )
		{
//do some stuff to build a model

HttpRequestMessageProperties odataProperties = request.ODataProperties();
			odataProperties.Model = model; // this can no longer be set here
			odataProperties.PathHandler = PathHandler;
			odataProperties.Path = path;
			odataProperties.RouteName = RouteName;
			odataProperties.RoutingConventions = RoutingConventions;
}
`

I apologize because it's almost guaranteed that I am doing this wrong. My understanding is that v6 should make this kind of thing easier? I just can't seem to figure out how I am supposed to set my dynamic model now.

Thanks for your help

**Comment by VikingsFan** [comment]
@rwmcdonald how to set the model:

first you should have a wrapper class the set the model :

     class ModelWrapper { IEdmModel Model {get;set;}}

put this class into container, and use this class to get model.


            configuration.MapODataServiceRoute("odata", "odata",
                builder =>
                    builder.AddService<ModelWrapper>(ServiceLifetime.Singleton)
                        .AddService(ServiceLifetime.Singleton, sp => sp.GetService<ModelWrapper>().Model)
                        .AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp =>
                            ODataRoutingConventions.CreateDefaultWithAttributeRouting("odata", configuration)));

then you can set model like:

    container.GetService<ModelWrapper>().Model = dynamic model;

**Comment by rwmcdonald** [comment]
OK a couple of questions here. I apologize but this whole Dependency Injection stuff is confusing me.

I want my model to be based on the user, it should be dynamically created for each request ( so I am using Scoped instead of Singleton ).

I tried your above code but it won't necessary work for me because I can't specify my model when I'm registering the route. Instead, the model needs to be set based off the request ( user ID ).

I tried setting a dummy model and then using GetService<ModelWrapper>().Model = dynamic model but that didn't seem to do anything, and I was still shown metadata for the dummy model.

Any advice would be much appreciated.

**Comment by VikingsFan** [comment]
@rwmcdonald you can set it in the route constraint, in the route constraint you can get container from request in match method.

**Comment by rwmcdonald** [comment]
I'm not sure it's possible to override the ODataRouteConstraint when using the service container method to map an ODataRoute.

I checked the [source](https://github.com/OData/WebApi/blob/OData60/OData/src/System.Web.OData/Extensions/HttpConfigurationExtensions.cs#L536) for MapODataServiceRoute and I see:

`
            ODataPathRouteConstraint routeConstraint = new ODataPathRouteConstraint(routeName);
`

Is it possible this is a bug? Shouldn't it be using GetService there so I can provide my own? 

If not, how am I supposed to provide my own ODataPathRouteConstraint?

Thanks again for your help

**Comment by rwmcdonald** [comment]
@VikingsFan 
Hey, just so you know I logged this as a separate [issue](https://github.com/OData/WebApi/issues/826). I do believe it's a bug because there is no way to use a custom one anymore. I can't update to new version of OData until it's fixed, or I find a workaround. ( which sucks, I want so many of the new features )

**Comment by azzlack** [comment]
I had the same problem. After I added `config.EnableDependencyInjection()` as per http://stackoverflow.com/questions/40504289/how-to-correctly-unit-test-odata-v6-0-controller everything worked.

**Comment by JohnGalt1717** [comment]
Thanks! That worked! Documentation on this is horrible. Major work needed!
