### ISSUE TITLE
Default sort order does not obey the Order of ColumnAttribute

### ISSUE THREAD

**Issue by jemerald** [OData/WebApi#841]
Our data model contains composite primary key across 3 columns. and the database (DB2) have very specific index on columns A+C+B.

Query runs very fast with `order by A ASC, C ASC, B ASC`, but very slow with `order by A ASC, B ASC, C ASC`.

The data model properties is decorated with `ColumnAttribute` with proper `Order` value, but the current version of OData applies the sorting order of `A ASC, B ASC, C ASC` by default.

### Assemblies affected
OData 7.0.0

### Reproduce steps
Create data model with following columns:

```C#
[Key]
[Column("A", Order = 1)]
public int A { get; set; }

[Key]
[Column("C", Order = 2)]
public DateTime C { get; set; }

[Key]
[Column("B", Order = 3)]
public DateTime B { get; set; }
```

Now query with no `$orderby` parameter

### Expected result
SQL executed contains `order by A ASC, C ASC, B ASC`

### Actual result
SQL executed contains `order by A ASC, B ASC, C ASC`

### Additional details
Looks like the columns are ordered alphabetically?

**Comment by NicosNet** [comment]
Hello, i have the same issue. 

Did you find a workaround ?

**Comment by jemerald** [comment]
@NicosNet no we haven't found a solution yet.

**Comment by NicosNet** [comment]
Thanks for your answer, maybe you can try to specifiy the order like [this](http://stackoverflow.com/questions/30814824/enforce-ordering-of-odata-items-even-when-top-is-used) it worked for me.

**Comment by bmillspaugh** [comment]
We are experiencing this issue and it is very bad for multi-key entities since OData often adds 2 order by clauses to the queries that are generated from SQL Server, and when they don't match the primary key order of the table SQL Server has to do a full table scan to get the correct results.

This applies any time you are using paging or have limits on the number of records returned by OData since it has to add an ORDER BY clause in order to produce the correct TOP results.  This means that it is happening in the background and makes it difficult to diagnose.

The fix for this should be pretty easy...order the fields in the ORDER BY clause based on the "Column" attribute's "Order" property (see screenshot in the first post of this thread).  You can work around it by adding your own ORDER BY clause, but that is NOT A SOLUTION and it is not something that we want to tell our customers who use our API.

Why is this issue still open almost a year later?  Is it being worked on?  It sounds like it would be a pretty quick fix, so it is hard to understand why it has not been fixed yet.

** If anyone knows where the code is that automatically adds the ORDER BY clause to all queries for paged results (or queries that use TOP) I think we could suggest a solution to this and get it fixed.
