### ISSUE TITLE
$top query option produces unexpected error when EnableQuery is used.

### ISSUE THREAD

**Issue by jtcalhoun** [OData/WebApi#862]
Attempting to use the `$top` query option in a controller action produces an `ODataException` with the message `"The limit of '0' for Top query has been exceeded."` even when a `MaxTop` value has been specified in a [Controller Level Query Setting](http://odata.github.io/WebApi/#controller-level-query-setting).

### Assemblies affected
System.Web.OData, v6.0.0.0

### Reproduce steps

- Create an OData controller action that uses the `EnableQuery` attribute to specify that the `$top` query option is allowed with a `MaxTop` value. (see example below)
- Navigate to the action using a `$top` value less than the `MaxTop` value specified.

```
namespace MyApp
{
	// using ...
	
	public class Product
	{
		[Key]
		public int Id { get; set; }
	}
	
	// Config...
	// var builder = ODataConventionModelBuilder();
	// builder.EntitySet<Product>("Products");
	// config.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());

	public class ProductsController : ODataController
	{
		[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Top, MaxTop = 20)]
		public IEnumerable<Product> Get(ODataQueryOptions opts)
		{
			var top = opts.Top != null ? opts.Top.Value : default(int);
			return new[] { new Product { Id = top } };
		}
	}
}
```

### Expected result
The action should return and OData response containing the number of entities specified by the `$top` query option.

### Actual result
When `$top` is a value from 1 to `MaxTop`, inclusive, an `ODataException` is thrown:

> http://localhost/odata/Products?$top=1 (Using the example above.)
>
> Error message: "The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '1'.

### Additional details

When `$top` is greater than `MaxTop`, the response is as expected:

> http://localhost/odata/Products?$top=21
> Error message: "The query specified in the URI is not valid. The limit of '20' for Top query has been exceeded. The value from the incoming request is '21'."

When `$top` is zero, the response is an empty array, as expected:

> http://localhost/odata/Products?$top=0
> Response: {"@odata.context":"http://localhost/odata/$metadata#Products","value":[]}

#### Possibly related: 
- #814 (The recommended solution (e.g. `config.MaxTop(20)`) enables `$top` for _all_ entities, which is not desired. Is requiring a global `MaxTop` value and enabling for all endpoints by design?)
- #823 
- https://github.com/OData/odata.net/issues/707

**Comment by glcheetham** [comment]
I'm experiencing similar unexpected behaviour with the `$top` query option.

Using `Microsoft.AspNet.OData v6.0.0` it seems that I cannot enable `$top` at all because I cannot set the `MaxTop` value to anything. OData always thinks that `MaxTop` is 0.

My error when performing HTTP GET with `$top`
```
{"error":{"code":"","message":"The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '10'.","innererror":{"message":"The limit of '0' for Top query has been exceeded. The value from the incoming request is '10'.","type":"Microsoft.OData.ODataException","stacktrace":"   at System.Web.OData.Query.Validators.TopQueryValidator.Validate(TopQueryOption topQueryOption, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.TopQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor, ODataQueryContext queryContext)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"}}}
```
### What I've Tried

As in [this question](http://stackoverflow.com/questions/39622599/odata-exception-the-limit-of-0-for-top-query-has-been-exceeded) Setting `config.Select().Expand().Filter().OrderBy().MaxTop(null).Count();` in the `WebApiConfig.cs` before `config.mapODataServiceRoute(...`. **Didn't work**.

Adding `[Page(MaxTop = 100)]` to my model as in the same question. **Didn't work**.

Setting `[Page]` attribute on model. From [WebApi OData documentation](http://odata.github.io/WebApi/#13-6x-Features-) "if you set the Page Attribute, by default it will enable the $top with no-limit maximum value". **Didn't work**. 

Setting `[EnableQuery(PageSize=10)]` attribute on controller. **Enabled paging but Didn't work**.

**The error says the limit was 0 for top in every case**

Follow-up stackoverflow question posted by myself RE: this [WebApi OData The limit of '0' for Top query has been exceeded, even after setting MaxTop](http://stackoverflow.com/questions/41849692/webapi-odata-the-limit-of-0-for-top-query-has-been-exceeded-even-after-settin)

**Comment by biaol-odata** [comment]
Close as duplicated of odata.net #707 and WebApi #814.
document: http://odata.github.io/WebApi/#13-01-modelbound-attribute

**Comment by xerere** [comment]
Replaced
`using Microsoft.AspNet.OData.Extensions; `
With
`using System.Web.OData.Extensions;  `
And it worked!
