### ISSUE TITLE
GroupBy does not project to then serialise IGroupings 

### ISSUE THREAD

**Issue by TehWardy** [OData/WebApi#868]
Adding odata $groupby=Foo to any query appears to still return a flat set.
Is this expected?

I've been binding my OData query results to Telerik controls and this breaks teleriks front end because it expects grouped sets instead the groupby clause appears to just do a sort as far as I can tell.

**Comment by biaol-odata** [comment]
Hi TehWardy,
Thanks for your support for OData. If I understand your context correctly, you are trying to do aggregation based on grouping, relevant to the protocol specified [here](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/csprd02/odata-data-aggregation-ext-v4.0-csprd02.html#_Toc378326304)? If so, $groupby cannot be used as query option, and you should probably try try $apply=groupby() semantic.

Another better place for OData questions is the public stackoverflow.com, since it is very popular for IT community.

Please write back / re-open the question if this is not the answer your are looking for. I will close this issue for now.
